---
model:
  base filters: 128
  channels: 3
train:
  noise level: 10
  patch size: 40 #antes 64
  batch size: 64
  learning rate: 1.e-4
  weight decay: 1.e-5
  scheduler gamma: 0.5
  scheduler step: 3
  epochs: 10
  dataset splits: 5
  device: cuda:0
  multi gpu: false
  workers: 0
  dataset path: 'Datasets/DIV2K_train_HR'
  checkpoint path: 'Checkpoints'
val:
  noise levels:
    - 10
  patch size: 40
  batch size: 1
  frequency: 1
  workers: 0
  dataset path: 'Datasets/DIV2K_valid_HR'
test:
  noise levels:
    - 30
    - 50
  device: cuda:0
  padding: true
  dataset path: 'Datasets/Test'
  results path: 'Results'
  pretrained models path: 'Pretrained'
  save images: true
...
